name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Gradle
      run: gradle createwrap
      #uses: gradle/actions/setup-gradle@v4
      #with: 
        #gradle-version: 8.12.1
        #gradle-version: 5.4
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        #gradle createwrap
    - name: 更新包列表并安装软件
      run: |
        sudo apt-get update
        sudo apt-get install tree
    - name: installtree
      uses: gerlero/apt-install@v1
      with:
        packages: tree
    - name: Build with Gradle
      run: 
        ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
        java -version
        #ls gradle
        #ls gradle/build
        #find / -name '*.apk'
        #./gradlew build
    - name: Organize the Files
      run: |
       echo {{ github.workspace }}
       echo $PWD
       mkdir -p ${{ github.workspace }}/apk/
       cp -rf ${{ github.workspace }}/app/build/outputs/apk/*/*/*.apk ${{ github.workspace }}/apk/
    - name: Push Assets To "release" Branch
      if: ${{ github.actor == 'ayuyas' }}
      run: |
        cd $GITHUB_WORKSPACE/apk/
        git init
        git checkout -b release
        git config --global user.name "github-actions[bot]"
        git config --global user.email "1782974138@qq.com"
        git remote add origin "https://${{ github.actor }}:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.actor }}/release"
        git add *.apk
        git commit -m "${{ env.VERSION }}"
        git push -f -u origin release
           
